name: Get bot token
description: Get GitHub App token of simple-icons[bot]

inputs:
  app_id:
    decription: GitHub App ID
    required: true
  private_key:
    description: GitHub App Private Key
    required: true

outputs:
  token:
    description: Bot token
    value: ${{ steps.app-token.outputs.token }}

runs:
  using: composite
  steps:
    - uses: actions/create-github-app-token@v1
      id: app-token
      with:
        app-id: ${{ inputs.app_id }}
        private-key: ${{ inputs.private_key }}
        env:
          APP_TOKEN: ${{ steps.app_token.outputs.token }}
        shell: sh
        run: |
          echo "token=$APP_TOKEN" >> $GITHUB_OUTPUT
