name: Test
on: push

jobs:
  testing:
    runs-on: ubuntu-latest
    name: Testing
    steps:
      - uses: actions/checkout@v4
      - run: realpath $(which corepack)
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: realpath $(which corepack)
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}

      - id: use-token
        run: |
          members="$(curl -H 'Authorization: Bearer ${{ steps.app-token.outputs.token }}' --retry 5 -s https://api.github.com/orgs/simple-icons/members | jq .[].login | tr '\n' ',' | sed -e 's/"//g' -e 's/,$//')"
          echo "members=$members" >> $GITHUB_OUTPUT
